CREATE TABLE CREDENTIALS(
	USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
	PASSWORD TEXT NOT NULL,
	UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE CREDENTIALS IS 'Stores secure authentication credentials.';
COMMENT ON COLUMN CREDENTIALS.USER_ID IS 'Foreign key referencing USERS.ID.';
COMMENT ON COLUMN CREDENTIALS.PASSWORD IS 'Cryptographic hash of the user password (e.g., Argon2id or Bcrypt output).';
COMMENT ON COLUMN CREDENTIALS.UPDATED_AT IS 'Timestamp with time zone indicating when the credential record was last modified.';

CREATE TRIGGER CREDENTIALS_BU_SET_UPDATED_AT
BEFORE UPDATE ON CREDENTIALS
FOR EACH ROW
EXECUTE FUNCTION GLOBAL_SET_UPDATED_AT();

COMMENT ON TRIGGER CREDENTIALS_BU_SET_UPDATED_AT ON CREDENTIALS IS 'Fires before any UPDATE on CREDENTIALS to automatically update the UPDATED_AT column using GLOBAL_SET_UPDATED_AT().';
