CREATE TABLE USERS_ROLES(
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID) ON DELETE CASCADE,
    GRANTED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID, ROLE_ID)
);

COMMENT ON TABLE USERS_ROLES IS 'Associative table mapping users to their assigned roles (Many-to-Many).';
COMMENT ON COLUMN USERS_ROLES.USER_ID IS 'Foreign key referencing USERS.ID.';
COMMENT ON COLUMN USERS_ROLES.ROLE_ID IS 'Foreign key referencing ROLES.ID.';
COMMENT ON COLUMN USERS_ROLES.GRANTED_AT IS 'Timestamp when the role was assigned to the user.';
