CREATE TABLE PERMISSIONS(
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    NAME TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE PERMISSIONS IS 'Defines granular action permissions (e.g., USERS:READ, ORDERS:CREATE).';
COMMENT ON COLUMN PERMISSIONS.ID IS 'Unique primary key identifier for the permission.';
COMMENT ON COLUMN PERMISSIONS.NAME IS 'Unique key identifying the permission action.';
COMMENT ON COLUMN PERMISSIONS.DESCRIPTION IS 'Description of what action this permission allows.';
COMMENT ON COLUMN PERMISSIONS.CREATED_AT IS 'Timestamp with time zone indicating when the permission record was created.';
COMMENT ON COLUMN PERMISSIONS.UPDATED_AT IS 'Timestamp with time zone indicating when the permission record was last modified.';

CREATE TRIGGER PERMISSIONS_BU_SET_UPDATED_AT
BEFORE UPDATE ON PERMISSIONS
FOR EACH ROW
EXECUTE FUNCTION GLOBAL_SET_UPDATED_AT();

COMMENT ON TRIGGER PERMISSIONS_BU_SET_UPDATED_AT ON PERMISSIONS IS 'Fires before any UPDATE on the PERMISSIONS table to automatically update the UPDATED_AT column using GLOBAL_SET_UPDATED_AT().';
