CREATE TABLE ROLES_PERMISSIONS(
    ROLE_ID UUID NOT NULL REFERENCES ROLES(ID) ON DELETE CASCADE,
    PERMISSION_ID UUID NOT NULL REFERENCES PERMISSIONS(ID) ON DELETE CASCADE,
    GRANTED_AT TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

COMMENT ON TABLE ROLES_PERMISSIONS IS 'Associative table mapping permissions to roles (Many-to-Many).';
COMMENT ON COLUMN ROLES_PERMISSIONS.ROLE_ID IS 'Foreign key referencing ROLES.ID.';
COMMENT ON COLUMN ROLES_PERMISSIONS.PERMISSION_ID IS 'Foreign key referencing PERMISSIONS.ID.';
COMMENT ON COLUMN ROLES_PERMISSIONS.GRANTED_AT IS 'Timestamp when the permission was granted to the role.';
